name: maskformer
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310h31b6992_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - anyio=4.12.1=pyhcf101f3_0
  - aom=3.9.1=hac33072_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py310h7c4b9e2_2
  - arrow=1.4.0=pyhcf101f3_0
  - assimp=6.0.3=hecf2907_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.2.0=pyhcf101f3_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - babel=2.18.0=pyhcf101f3_0
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - bleach=6.3.0=pyhcf101f3_1
  - bleach-with-css=6.3.0=hbca2aae_1
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.2.25=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he90730b_1
  - certifi=2026.2.25=pyhd8ed1ab_0
  - cffi=2.0.0=py310he7384ee_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cli11=2.6.0=h54a6638_0
  - click=8.3.1=pyh8f84b5b_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py310h3788b33_0
  - cuda-version=12.9=h4f385c5_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dash=4.0.0=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h24cb091_1
  - debugpy=1.8.20=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - double-conversion=3.4.0=hecca717_0
  - eigen=3.4.0=h54a6638_2
  - embree=4.4.0=ha751380_1
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.4=h7354ed3_0
  - ffmpeg=8.0.1=gpl_heab3d61_711
  - flann=1.9.2=hc299af7_5
  - flask=3.1.3=pyhcf101f3_1
  - fmt=12.1.0=hff5e90c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.17.1=h27c8c51_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h3406613_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freeglut=3.2.2=ha6d2627_3
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - frozenlist=1.7.0=py310h9548a50_0
  - gcc_impl_linux-64=15.2.0=hcacfade_7
  - gcc_linux-64=15.2.0=h862fb80_21
  - gdk-pixbuf=2.44.5=h2b0a6b4_1
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.3.0=h71661d4_0
  - glfw=3.4=hb03c661_1
  - glslang=16.2.0=hfd11570_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - gxx_impl_linux-64=15.2.0=h54ccb8d_7
  - gxx_linux-64=15.2.0=h1fb793f_21
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py310h4aa865e_101
  - harfbuzz=12.3.2=h6083320_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h19486de_106
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=hde8ca8f_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - ipykernel=7.2.0=pyha191276_1
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jasper=4.2.8=he3c4edf_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - json5=0.13.0=pyhd8ed1ab_0
  - jsoncpp=1.9.6=hf42df4d_1
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.26.0=hcf101f3_0
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyter_events=0.12.0=pyhe01879c_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.4=pyhcf101f3_0
  - jupyterlab=4.5.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lark=1.3.1=pyhd8ed1ab_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.28.0=hb700be7_0
  - libabseil=20260107.1=cxx17_h7b12aa8_0
  - libaec=1.1.5=h088129d_0
  - libass=0.17.4=h96ad9f0_0
  - libavif16=1.3.0=h316e467_3
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libboost=1.88.0=hd24cca6_7
  - libboost-devel=1.88.0=hfcd1e18_7
  - libboost-headers=1.88.0=ha770c72_7
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.5.2=h3435931_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=15.2.0=h73f6952_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_18
  - libgfortran5=15.2.0=h68bc16d_18
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglib=2.86.4=h6548e54_1
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libhwy=1.3.0=h4c17acf_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libjxl=0.11.2=ha09017c_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - libllvm20=20.1.8=hf7376ad_1
  - libllvm21=21.1.8=hf7376ad_0
  - liblzf=3.6=hb9d3cd8_3
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnetcdf=4.9.3=nompi_hbf2fc22_104
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopencv=4.13.0=qt6_py310h4c6fe98_602
  - libopengl=1.7.0=ha4b6fd6_2
  - libopengl-devel=1.7.0=ha4b6fd6_2
  - libopenvino=2025.4.1=hb56ce9e_2
  - libopenvino-auto-batch-plugin=2025.4.1=hd85de46_2
  - libopenvino-auto-plugin=2025.4.1=hd85de46_2
  - libopenvino-hetero-plugin=2025.4.1=hd41364c_2
  - libopenvino-intel-cpu-plugin=2025.4.1=hb56ce9e_2
  - libopenvino-intel-gpu-plugin=2025.4.1=hb56ce9e_2
  - libopenvino-intel-npu-plugin=2025.4.1=hb56ce9e_2
  - libopenvino-ir-frontend=2025.4.1=hd41364c_2
  - libopenvino-onnx-frontend=2025.4.1=h7a07914_2
  - libopenvino-paddle-frontend=2025.4.1=h7a07914_2
  - libopenvino-pytorch-frontend=2025.4.1=hecca717_2
  - libopenvino-tensorflow-frontend=2025.4.1=h78e8023_2
  - libopenvino-tensorflow-lite-frontend=2025.4.1=hecca717_2
  - libopus=1.6.1=h280c20c_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.55=h421ea60_0
  - libpq=18.2=hb80d175_0
  - libprotobuf=6.33.5=h2b00c02_0
  - librsvg=2.60.2=h61e6d4b_0
  - libsanitizer=15.2.0=hb13aed2_7
  - libsndfile=1.2.2=hc7d488a_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_107
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libsystemd0=259.1=h6569c3e_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.7.1=h9d88235_1
  - libudev1=259.1=h6569c3e_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.13=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.3=h5347b49_0
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.15.2=hecca717_0
  - libvulkan-loader=1.4.341.0=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb25bd0a_0
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib=3.10.8=py310hff52083_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mesalib=25.0.5=h57bcd07_2
  - mistune=3.2.0=pyhcf101f3_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.2=py310h03d9f68_1
  - multidict=6.7.1=py310h3406613_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nanoflann=1.6.1=hff21bea_0
  - narwhals=2.17.0=pyhcf101f3_0
  - nbclient=0.10.4=pyhd8ed1ab_0
  - nbconvert-core=7.17.0=pyhcf101f3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h54a6638_1
  - notebook=7.5.4=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.2.6=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openexr=3.4.5=h40f6f1d_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openjph=0.26.3=h8d634f6_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.1=h35e630c_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - pandas=2.3.3=py310h0158d43_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.4=hadf4263_0
  - parso=0.8.6=pyhcf101f3_0
  - pcl=1.15.1=h717c489_6
  - pcre2=10.47=haa7fec5_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=12.1.1=py310h5a73078_0
  - pip=26.0.1=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.9.2=pyhcf101f3_0
  - plotly=6.5.2=pyhd8ed1ab_0
  - proj=9.7.1=he0df7b0_3
  - prometheus_client=0.24.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - prompt_toolkit=3.0.52=hd8ed1ab_0
  - propcache=0.3.1=py310h89163eb_0
  - psutil=7.2.2=py310h139afa4_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.13.0=qt6_py310h05d4700_602
  - pybind11-abi=11=hc364b38_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.2=py310h2007e60_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h3406613_1
  - pyzmq=27.1.0=py310hc4bea81_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.2=hb82b983_4
  - rav1e=0.7.1=h8fae777_3
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=pyhcf101f3_1
  - retrying=1.4.2=pyhe01879c_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.30.0=py310hd8f68c5_0
  - scikit-learn=1.7.2=py310h228f341_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.4.0=h3b84278_0
  - send2trash=2.1.0=pyha191276_1
  - setuptools=80.10.2=py310h06a4308_0
  - shaderc=2025.5=h3e344bc_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.3=pyhd8ed1ab_0
  - spirv-tools=2025.5=hb700be7_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=4.0.0=hecca717_0
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tbb=2022.3.0=hb700be7_2
  - tbb-devel=2022.3.0=h51de99f_2
  - terminado=0.18.1=pyhc90fa1f_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tinyobjloader=1.0.7=h59595ed_2
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py310ha78b2d2_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025c=he532380_0
  - unicodedata2=17.0.1=py310h7c4b9e2_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - utfcpp=4.09=ha770c72_0
  - viskores=1.1.0=cuda12.9_h14fae2a_
  - vtk=9.5.2=py310h6b228f0_7
  - vtk-base=9.5.2=py310h3c48d7e_7
  - vtk-io-ffmpeg=9.5.2=py310haf7eeca_7
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.47=hd8ed1ab_0
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - werkzeug=3.1.6=pyhcf101f3_0
  - wheel=0.46.3=py310h06a4308_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - wslink=2.5.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.6=hecca717_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - zeromq=4.3.5=h387f397_9
  - zfp=1.0.1=h909a3a2_5
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - addict==2.4.0
      - aiofiles==24.1.0
      - alabaster==1.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - black==26.1.0
      - blosc2==4.0.0
      - cmake==4.2.1
      - configargparse==1.7.1
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.5
      - cython==3.2.4
      - depth-clustering==1.0.0
      - docutils==0.21.2
      - einops==0.8.2
      - fastapi==0.133.0
      - ffmpy==1.0.0
      - filelock==3.24.3
      - flake8==7.3.0
      - fsspec==2026.2.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - gradio==6.6.0
      - gradio-client==2.1.0
      - groovy==0.1.2
      - hf-xet==1.3.1
      - huggingface-hub==1.4.1
      - imageio==2.37.2
      - imagesize==1.4.1
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - ipython==8.38.0
      - librt==0.8.1
      - markdown-it-py==4.0.0
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - ndindex==1.10.1
      - networkx==3.4.2
      - ninja==1.13.0
      - numexpr==2.14.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.4.127
      - open3d==0.19.0
      - opencv-python==4.13.0.92
      - orjson==3.11.7
      - packaging==26.0
      - pathspec==1.0.4
      - pluggy==1.6.0
      - protobuf==6.33.5
      - py-cpuinfo==9.0.0
      - pybind11==3.0.2
      - pycodestyle==2.14.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pyflakes==3.4.0
      - pyquaternion==0.9.9
      - pytest==9.0.2
      - python-multipart==0.0.22
      - pytokens==0.4.1
      - rich==14.3.3
      - ruff==0.15.2
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentry-sdk==2.53.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.1.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - starlette==0.52.1
      - sympy==1.13.1
      - tables==3.10.1
      - tabulate==0.9.0
      - termcolor==3.3.0
      - timm==1.0.25
      - tomlkit==0.13.3
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchvision==0.21.0+cu124
      - trimesh==4.11.2
      - triton==3.2.0
      - typer==0.24.1
      - typer-slim==0.24.0
      - typing-inspection==0.4.2
      - uvicorn==0.41.0
      - wandb==0.25.0
      - websockets==16.0
prefix: /data/home/mahsa/miniconda3/envs/maskformer
